$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
    - node_modules
    - bun.lockb
    - .tsbuildinfo
    - .gitignore
    - .next
    - drizzle
    - '**/*.svg'
    - .vscode/extensions.json
    - public
    - tsconfig.tsbuildinfo
    - branch_out
words:
    - activecampaign
    - adipisicing
    - aeiou
    - Arcjet
    - asana
    - autopilotmail
    - autoresponder
    - banlist
    - Banlist
    - BANLIST
    - bcdfghj
    - bigcommerce
    - callees
    - classname
    - clsx
    - cmdk
    - commitlint
    - compat
    - constantcontact
    - customerservice
    - eioluseyi
    - embla
    - Embla
    - esbenp
    - facebookmail
    - freshdesk
    - frontmatter
    - greatenv
    - healthcheck
    - helpdesk
    - helpscout
    - hookform
    - hubspot
    - ianvs
    - identifer
    - ixahmedxi
    - ixahmedxii
    - jiti
    - lockb
    - lucide
    - mailchimp
    - mailgun
    - marketo
    - mitigations
    - mpin
    - neondatabase
    - nextjs
    - nocompatible
    - noreplys
    - notespace
    - nums
    - packagejson
    - paralleldrive
    - pinterest
    - pipedrive
    - Posthog
    - postmarkapp
    - preferredstrategy
    - preprod
    - PREPROD
    - pseudoelements
    - Quisquam
    - radact
    - ratelimit
    - redditmail
    - Registrator
    - Rohit
    - sendgrid
    - sendinblue
    - serviceworker
    - Shadcn
    - Signin
    - Signup
    - Sonner
    - SQUARICLE
    - sslmode
    - superjson
    - tailwindcss
    - tanstack
    - tawk
    - timeago
    - Tiwari
    - Todos
    - trpc
    - tsbuildinfo
    - tseslint
    - turbopack
    - typecheck
    - Uploadthing
    - Upstash
    - usehooks
    - vaul
    - webstorage
    - yopmail
    - msapplication
    - devnotespace
    - coudinary
    - formschemas
