import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
// import { Toaster } from "@/components/ui/toaster";
import Providers from "@/lib/providers";

/* Fonts Declarations */
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Notespace",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={`${geistSans.variable} ${geistMono.variable}`}
			style={{ colorScheme: "dark" }}
		>
			<body>
				<Providers>
					{/* <Toaster richColors /> */}
					{children}
				</Providers>
			</body>
		</html>
	);
}
